#!/usr/bin/env python3
"""Generate the Togaviridae block of Viral_PSSM.json.

Everything here is derived from files in this directory, so the JSON can be
regenerated byte-identically after any rebuild:

    collections/report.tsv     length bounds
    cutoff_measurements.json   the signal/noise window each bit_cutoff sits in
    rep_contigs.json           close_genomes
    Alignments/<M>/<F>/pssms/  which features actually have profiles

Written in the canonical format -- JSON::XS pretty + canonical: 3-space indent,
" : " between key and value, keys sorted at every level -- so a Perl tool
rewriting the master produces no spurious diff.
"""
import glob, json, os, sys

MOD = "Togaviridae"

# ==========================================================================
# ANNOTATION STRINGS
# ==========================================================================
# Two are REUSED verbatim from the controlled vocabulary rather than coined:
#
#   RNA-dependent RNA polymerase   for nsP4. Already carried by 12 taxa, and
#                                  used for a mat_peptide by the coronavirus
#                                  modules (NSP12), so the precedent for a
#                                  cleavage product carrying it exists.
#   Nucleocapsid protein           for C. The alphavirus capsid binds the
#                                  genome and forms the nucleocapsid core;
#                                  coining "Capsid protein" beside the existing
#                                  string would add a vocabulary entry for a
#                                  protein the vocabulary already names.
#
# Nine are new. Each one says only what the SOURCE DATA already asserts, which
# is the rule for a functional claim with no DLIT a human has read:
#
#   nsP1  BV-BRC says "mRNA-capping enzyme nsp1" on 7,384 features, so the
#         capping claim is the submitters', not ours.
#   nsP2  BV-BRC says "protease nsp2" on 8,255 features. nsP2 is also an RNA
#         helicase, NTPase and RNA triphosphatase and is the transcriptional
#         shutoff factor, but none of that is in the source and all of it would
#         rest on citations nobody here has read -- so the string stays at
#         "Protease". The helicase PMIDs ride along on the feature, flagged, so
#         a curator can promote the name later.
#   nsP3  BV-BRC says only "non-structural protein nsp3". The macrodomain,
#         zinc-binding domain and hypervariable host-factor-binding domain are
#         all real and all absent from the source, so the annotation makes no
#         functional claim at all. Same reasoning, same remedy.
#   E1/E2/E3  "Mature envelope glycoprotein E<n>". E1 is the class II fusion
#         protein and E2 carries the receptor-binding site; neither claim is in
#         the source, and "Mature C-terminal envelope glycoprotein Gc" in the
#         vocabulary shows that a positional/symbolic form without a functional
#         claim is the house style for a cleaved envelope product.
#   6K    the source's own words, in the vocabulary's "Mature " form. 6K's
#         viroporin activity is documented but, again, not by anything read
#         here.
#   P1234 / SP  the two precursors, named as the vocabulary names precursors
#         ("ORF1ab polyprotein", "Pre-glycoprotein polyprotein GP complex").
#         NOTE the nonstructural one is "Nonstructural polyprotein" and NOT
#         "... P1234" -- see THE OPAL CODON below. Naming it P1234 would be
#         wrong on seven alphaviruses in eight.
#
# No taxon prefix on any of them: the current vocabulary revision removed those.
# ==========================================================================
ANNO = {
    "NSP1234": ("Nonstructural polyprotein",             "nsP1234", "CDS"),
    "NSP1":    ("mRNA-capping enzyme nsP1 protein",      "nsP1",    "mat_peptide"),
    "NSP2":    ("Protease nsP2 protein",                 "nsP2",    "mat_peptide"),
    "NSP3":    ("Nonstructural protein nsP3",            "nsP3",    "mat_peptide"),
    "NSP4":    ("RNA-dependent RNA polymerase",          "nsP4",    "mat_peptide"),
    "STP":     ("Structural polyprotein",                "STP",     "CDS"),
    "C":       ("Nucleocapsid protein",                  "C",       "mat_peptide"),
    "E3":      ("Mature envelope glycoprotein E3",       "E3",      "mat_peptide"),
    "E2":      ("Mature envelope glycoprotein E2",       "E2",      "mat_peptide"),
    "6K":      ("Mature 6K membrane protein",            "6K",      "mat_peptide"),
    "E1":      ("Mature envelope glycoprotein E1",       "E1",      "mat_peptide"),
    # --- multi-product intermediates -------------------------------------
    # Real proteins made of adjacent products, recovered from their flanking
    # calls because the source export holds almost nothing for either.
    #   pE2 (p62) = E3+E2. The furin-uncleaved precursor that heterodimerises
    #     with E1 and traffics; furin cleavage is late and, in some alphaviruses,
    #     incomplete. Generality is established from the data rather than
    #     asserted: a canonical furin site R-X-[KR]-R closes 91% of E3 sequences
    #     (93% counting the minimal form) across 39 species, and in 30 of those
    #     species EVERY E3 carries one. A precursor that is furin-cleaved
    #     genus-wide must form genus-wide.
    #   P123 = nsP1+nsP2+nsP3, the opal-terminated product. Established by the
    #     module's one curator-read DLIT (37862073), which states readthrough is
    #     necessary to produce full-length nsP3 and nsP4 -- i.e. without it,
    #     P123 is what is made.
    "PE2":     ("Envelope glycoprotein precursor pE2",   "pE2",     "mat_peptide"),
    "P123":    ("Nonstructural polyprotein P123",        "nsP123",  "CDS"),
}
ORDER = ["NSP1234", "P123", "NSP1", "NSP2", "NSP3", "NSP4",
         "STP", "PE2", "C", "E3", "E2", "6K", "E1"]

# ==========================================================================
# THE OPAL CODON, AND WHY THE NONSTRUCTURAL POLYPROTEIN IS NOT CALLED "P1234"
#
# Most alphaviruses carry an in-frame opal (UGA) codon at the nsP3/nsP4
# junction. P123 terminates there and is the primary translation product;
# P1234 exists only by ribosomal readthrough of that codon. Chikungunya,
# O'nyong-nyong, Semliki Forest and the salmonid alphaviruses carry a sense
# codon instead and translate P1234 directly.
#
# This is not a curiosity, it is the majority case. Measured on the 39
# RefSeq alphavirus genomes, the nonstructural polyprotein this module calls:
#
#     2432-2602 aa (P1234, no opal)      5 genomes   NC_004162 NC_001512
#                                                    NC_003215 NC_003930 NC_003433
#     1785-2022 aa (P123, opal)         34 genomes
#
# The annotator cannot emit the readthrough form on an opal genome, and this
# was checked in the code rather than assumed. Two independent mechanisms stop
# it: the PSSM path crops a hit at an internal stop
# (`if (($hseq =~ /\*/) && (! $keep_stop))`), and the coordinate-anchored path
# refuses any derived protein containing one at all
# (`if ($prot =~ /\*(?!$)/) { ... No assignment made ... }`). So declaring
# P1234 as a feature anchored from nsP1's start to nsP4's stop -- the obvious
# fix, and the mechanism Arenaviridae GP1 uses -- produces nothing on exactly
# the genomes that need it. -keep_stop is a global flag, not a per-feature one,
# so it cannot be used for this either.
#
# What the module therefore declares is ONE feature for the nonstructural ORF,
# whose extent is what the ribosome makes before it stops, with length bounds
# spanning both products and an annotation that claims neither: "Nonstructural
# polyprotein", symbol nsP1234 for the ORF. Nothing is lost by this -- nsP1,
# nsP2, nsP3 and nsP4 are each called from their own profiles and each is
# correct in both genome types. On Sindbis (opal at 5751-5753): nsP3 ends
# 5750, nsP4 starts 5769, the polyprotein is called 60-5750, and GenBank's own
# P123 CDS is 60..5750.
#
# Separating P123 from P1234 needs a readthrough-aware caller. That is an
# annotator change, not a module change, and it is recorded in BUILD_NOTES.md
# as the one thing this module cannot do.
# ==========================================================================

# ==========================================================================
# EXTENSION FLAGS
#
# The alphavirus genome is two polyproteins, each cleaved into a tiling set of
# mature peptides. Chikungunya NC_004162 measured from the source:
#
#   P1234  77..7501   nsP1 77..1681 | nsP2 1682..4075 | nsP3 4076..5665 | nsP4 5666..7498
#   SP   7567..11313     C 7567..8349 | E3 8350..8541 | E2 8542..9810 | 6K 9811..9993 | E1 9994..11310
#
# They tile exactly, and each precursor's last product ends three bases short of
# it -- the stop codon. So, applying the rule from references/json-schema.md:
#
#   the two CDS precursors        initiating Met .. stop          1 / 1
#   nsP1 and C, the FIRST product same Met .. a cleavage site     1 / 0
#   nsP2, nsP3, E3, E2, 6K        cleavage .. cleavage            0 / 0
#   nsP4 and E1, the LAST product cleavage .. the precursor's own
#                                 stop codon                      0 / 1
#
# The last-product case is the one the schema table and the step-14 measurement
# disagree about. The table says 0, "a mature peptide never includes the stop
# codon". The Alpharhabdovirinae measurement says 0 let 40% of mature G calls
# drift off the precursor's stop by a median of 28 codons, and 1 fixed it. The
# difference is that nsP4's and E1's C-termini are NOT protease sites -- nothing
# marks them but the stop codon, which is exactly what downstream_ext is for.
# Set to 1 here and verified by check_cleaved_ends.py; see BUILD_NOTES.md.
#
# That the collections' own N-terminal residues come out as they do is the
# independent check that these boundaries are real:
#   nsP1 M 94%   nsP2 G 87%/A 12%   nsP3 A 99%   nsP4 Y 99%
#   C    M 96%   E3   S 79%         E2   S 86%   6K A/E/D    E1 Y 91%
# nsP4's invariant N-terminal Tyr and nsP3's invariant Ala are the documented
# nsP2-protease sites; E2's Ser is the furin site in PE2; E1's Tyr and 6K's
# small residue are signal-peptidase sites.
# ==========================================================================
# ==========================================================================
# internal_stop : 1 -- keep a single internal stop rather than cropping there.
#
# Set on exactly the two features whose match spans the nsP3 opal: nsP3 itself,
# and the nonstructural polyprotein that contains it. Deliberately NOT written
# as "internal_stop" : 0 on the other nine. With the annotator defaulting to 0,
# absent and 0 behave identically, and the repo's own convention is to omit an
# inapplicable field -- copy_num appears on 284 of 490 features, special on 45.
# Omitting it means `grep internal_stop` returns exactly the features that
# permit one, which is the question an auditor actually asks; writing the zeros
# would make that grep return everything and force a read of values instead.
#
# nsP4 does not need it: it begins AFTER the opal, so its match never contains
# one. Nor does the structural polyprotein or any of its products.
# ==========================================================================
INTERNAL_STOP = {"NSP3": 1, "NSP1234": 1}

EXT = {
    "NSP1234": (1, 1), "NSP1": (1, 0), "NSP2": (0, 0), "NSP3": (0, 0), "NSP4": (0, 1),
    "STP":     (1, 1), "C":    (1, 0), "E3":   (0, 0), "E2":   (0, 0), "6K":   (0, 0),
    "E1":      (0, 1),
    #  pE2: both termini are cleavages -- the capsid autoprotease site at its
    #  start, the furin site at its end. 0/0.
    "PE2":     (0, 0),
    #  P123: starts at the polyprotein's own initiating Met, so 1 upstream. Its
    #  C-terminus is the nsP2 cleavage site, NOT a stop codon -- downstream_ext
    #  must be 0, because in an opal-free genome scanning onward would run past
    #  nsP3 to the polyprotein's real stop and emit P1234 under P123's name.
    "P123":    (1, 0),
}

# ==========================================================================
# bit_cutoff, from measure_cutoffs.py: above the noise ceiling, below the
# weakest true signal, erring toward specificity. The window each one sits in
# is written into the build notes rather than guessed at.
# ==========================================================================
BIT = {"NSP1234": 1500, "NSP1": 300, "NSP2": 400, "NSP3": 150, "NSP4": 150,
       "STP": 600, "PE2": 200, "P123": 900, "C": 100, "E3": 45, "E2": 150, "6K": 38, "E1": 250}

# Length bounds: the collection's own observed range, widened by ~3% each way
# so a slightly longer or shorter real protein is not flagged by the quality
# tool. Numbers come from collections/report.tsv, not from a textbook.
PAD = 0.03

# ==========================================================================
# CITATIONS
#
# Every PMID here was proposed by a language model, so every one is listed in
# PMID_claude_generated as well as PMID. None has been read by a curator, and
# under the rule in references/annotation-vocabulary.md that is why no
# annotation string above makes a functional claim the source data does not
# already make. Clearing an entry from this registry is what removes its flag,
# so unflagging is a deliberate act.
# ==========================================================================
# 37862073 is deliberately ABSENT from this registry. A curator supplied it and
# read it; that is what a DLIT is, and keeping it out of CLAUDE_PMIDS is the act
# that clears the flag. Li, Sun, Tuplin & Harris 2023 J Gen Virol, "A structural
# and functional analysis of opal stop codon translational readthrough during
# Chikungunya virus replication" -- it establishes that readthrough occurs at
# ~10% and is required for full-length nsP3 AS WELL AS nsP4, and that the opal
# is replaced by an arginine codon (AGA or CGA) in other isolates.
CLAUDE_PMIDS = {
    "12917405":  "Vasiljeva et al. 2003 JBC, Regulation of the sequential processing of Semliki Forest virus replicase polyprotein",
    "2141206":  "Shirako & Strauss 1990 Virology, Cleavage between nsP1 and nsP2 initiates the processing pathway of Sindbis virus nonstructural proteins",
    "23864626":  "Snyder et al. 2013 J Virol, The role of E3 in pH protection during alphavirus assembly and exit",
    "21430054":  "Uchime et al. 2011 J Virol, Activation of the alphavirus spike protein is suppressed by bound E3",
    "21124458":  "Voss et al. 2010 Nature, Glycoprotein organization of Chikungunya virus particles revealed by X-ray crystallography",
    "3553612":  "Melancon & Garoff 1987 J Virol, Processing of the Semliki Forest virus structural polyprotein: role of the capsid protease",
    "1985194":  "Liljestrom & Garoff 1991 J Virol, Internally located cleavable signal sequences direct formation of Semliki Forest virus membrane proteins",
    "7241658":  "Garoff et al. 1981 J Virol, Evidence for a separate signal sequence for the C-terminal envelope glycoprotein E1 of Semliki Forest virus",
    "2200886":  "Lobigs et al. 1990 J Virol, Function of Semliki Forest virus E3 peptide in virus assembly; replacement of E3 with an artificial signal peptide",
    "23035234":  "Snyder et al. 2012 J Virol, The alphavirus E3 glycoprotein functions in a clade-specific manner",
    "7968923":  "Strauss & Strauss 1994 Microbiol Rev, The alphaviruses: gene expression, replication, and evolution",
    "6322438":  "Strauss et al. 1984 Virology, Complete nucleotide sequence of the genomic RNA of Sindbis virus",
    "12466484": "Khan et al. 2002 J Gen Virol, Complete nucleotide sequence of chikungunya virus",
    "12021349": "Weston et al. 2002 J Virol, Comparison of salmon pancreas disease virus and sleeping disease virus",
    "10357827": "Ahola et al. 1999 EMBO J, Semliki Forest virus mRNA capping enzyme requires anionic membrane phospholipids",
    "36792007": "Zhang et al. 2023 J Mol Biol, Self-inhibited state of VEEV nsP2 cysteine protease",
    "30825649": "Makrynitsa et al. 2019 J Struct Biol, Conformational plasticity of the VEEV macro domain",
    "19036396": "Rubach et al. 2009 Virology, Purified Sindbis virus nsP4 RNA-dependent RNA polymerase activity in vitro",
    "9094737":  "Choi et al. 1997 Proteins, Structure of Semliki Forest virus core protein",
    "8627739":  "Heidner & Johnston 1996 J Virol, Differential processing of Sindbis virus glycoprotein PE2",
    "11301009": "Lescar et al. 2001 Cell, The fusion glycoprotein shell of Semliki Forest virus",
    "18822126": "Firth et al. 2008 Virol J, Discovery of frameshifting in Alphavirus 6K",
    "23720714": "Snyder et al. 2013 J Virol, Functional characterization of the alphavirus TF protein",
}
# Every id above was checked to RESOLVE TO THE PAPER NAMED, after an earlier
# pass put five plausible-looking numbers in that resolved to a bacterial
# cytoskeleton paper, an octopus haemocyanin cDNA and a peptide synthetase.
# check_dlits.py caught all five. Resolving an id is still not reading the
# paper, so every one stays flagged.
PMID = {
    "NSP1234": ["7968923", "6322438", "12466484", "12021349", "37862073"],
    "NSP1":    ["7968923", "10357827"],
    "NSP2":    ["7968923", "36792007"],
    "NSP3":    ["7968923", "30825649", "37862073"],
    "NSP4":    ["7968923", "19036396", "37862073"],
    "STP":     ["7968923", "6322438", "12466484", "12021349"],
    "C":       ["7968923", "9094737", "3553612"],
    "E3":      ["7968923", "8627739", "2200886", "23035234"],
    "E2":      ["7968923", "8627739", "1985194"],
    "6K":      ["7968923", "18822126", "7241658", "1985194"],
    "E1":      ["7968923", "11301009", "7241658"],
    "PE2":     ["7968923", "8627739", "21430054", "23864626", "21124458"],
    "P123":    ["37862073", "7968923", "2141206", "12917405"],
    "TF":      ["18822126", "23720714", "7968923"],
}

# ==========================================================================
# FEATURES CALLED BY AN EXTERNAL PROGRAM
#
# TF is made by a -1 ribosomal frameshift at a conserved UUUUUUA heptamer
# inside 6K (Firth 2008), so it is not collinear with the genome in any single
# frame and no PSSM can call it: tblastn splits a TF query into two HSPs in
# frames 1 and 3. get_transcript_edited_features.pl handles it instead, by
# blastn-ing a curated nucleotide reference that carries one extra templated
# base and filling the resulting subject gap from the query.
#
# Note that "transcript_edit" is the kit's mechanism, not a claim about the
# biology. A paramyxovirus V mRNA really does differ from its template -- the
# polymerase inserts a non-templated G. Nothing edits the alphavirus message;
# the ribosome re-reads one templated base. The two are informationally
# identical, which is why the same machinery serves both, but there is no such
# thing as an edited alphavirus transcript to go looking for.
#
# mat_peptide, not CDS: TF has no initiating Met. Its N-terminus is made by
# signal peptidase at the E2/6K junction -- the same cut that makes 6K's -- so
# the reference starts GCC, exactly as the coronavirus NSP12 references start
# TCA/AGT. Its C-terminus, unlike NSP12's, IS a stop codon, so the reference
# keeps it and the protein carries a trailing "*" -- the ssGP convention, and
# the same thing the scan-to-stop features (nsP1234, STP, nsP4, E1) do.
# min/max span the 62-100 residues observed across 234 constructed references;
# 76 is the mode (151 of 234) and the divergent salmonid alphaviruses hold the
# long tail at 93-100.
# ==========================================================================
SPECIAL = {
    "TF": {
        "anno":         "TransFrame protein",
        "gene_symbol":  "TF",
        "feature_type": "mat_peptide",
        "special":      "transcript_edit",
        "min_len":      55,
        "max_len":      110,
    },
}

SEGMENT = "Single RNA Segment"


def attach_pmids(d, key):
    """The two lists are DISJOINT, not nested. PMID holds citations a curator
    supplied and read -- actual DLITs. PMID_claude_generated holds proposals a
    model made, which are not DLITs however real the paper is. Listing a
    proposed id in both fields duplicates it and blurs exactly the distinction
    the second field exists to draw; a consumer reading PMID would take the
    proposals as curated."""
    ids = [str(x) for x in PMID.get(key, [])]
    human    = [i for i in ids if i not in CLAUDE_PMIDS]
    proposed = [i for i in ids if i in CLAUDE_PMIDS]
    if human:
        d["PMID"] = human
    if proposed:
        d["PMID_claude_generated"] = proposed


def canonical(obj):
    """JSON::XS pretty+canonical, byte for byte."""
    def norm(o):
        if isinstance(o, dict):  return {k: norm(v) for k, v in o.items()}
        if isinstance(o, list):  return [norm(v) for v in o]
        if isinstance(o, float) and o.is_integer(): return int(o)
        return o
    return json.dumps(norm(obj), indent=3, separators=(",", " : "),
                      sort_keys=True, ensure_ascii=False) + "\n"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    os.chdir(here)

    bounds = {}
    for i, line in enumerate(open("collections/report.tsv")):
        if i == 0: continue
        p = line.rstrip("\n").split("\t")
        bounds[p[0]] = (int(p[4]), int(p[6]))     # min_aa, max_aa
    # The collection holds only full-length P1234 (2302-2636 aa), because that
    # is what a profile should be trained on. The FEATURE, though, is whatever
    # the ribosome makes before it stops, and on an opal genome that is P123 --
    # 1785 aa at the short end across the RefSeq panel. Bounding the feature by
    # its collection would flag seven genomes in eight as "too short" for
    # having the normal alphavirus genome organisation.
    bounds["NSP1234"] = (1750, bounds["NSP1234"][1])

    have_pssm = {f for f in ORDER
                 if glob.glob(f"Alignments/{MOD}/{f}/pssms/*.pssm")}
    missing = [f for f in ORDER if f not in have_pssm]
    if missing:
        sys.exit("features declared with no PSSM: %s -- refusing to write" % missing)

    close = {}
    for r in json.load(open("rep_contigs.json")):
        close[r["file"]] = {"genome_ids": r["genome_ids"],
                            "genome_name": r["genome_name"]}

    feats = {}
    for key in ORDER:
        anno, sym, ftype = ANNO[key]
        lo, hi = bounds[key]
        up, down = EXT[key]
        d = {
            "anno": anno,
            "gene_symbol": sym,
            "feature_type": ftype,
            "segment": SEGMENT,
            "bit_cutoff": BIT[key],
            "coverage_cutoff": 0.65,
            "upstream_ext": up,
            "downstream_ext": down,
            "copy_num": 1,
            "kmers": 1,
            "min_len": int(lo * (1 - PAD)),
            "max_len": int(hi * (1 + PAD)) + 1,
        }
        if key in INTERNAL_STOP:
            d["internal_stop"] = INTERNAL_STOP[key]
        attach_pmids(d, key)
        feats[key] = d

    # A special feature declares no bit_cutoff, no coverage_cutoff and no
    # extensions: none of those fields is read for a feature the PSSM pass
    # never sees. install_module.py --check knows not to demand a PSSM for one.
    for key, spec in SPECIAL.items():
        d = dict(spec)
        d["segment"] = SEGMENT
        attach_pmids(d, key)
        feats[key] = d

    block = {MOD: {
        "close_genomes": close,
        "segments": {SEGMENT: {"min_len": 10000, "max_len": 13000,
                               "replicon_geometry": "linear"}},
        "features": feats,
    }}
    open("Togaviridae_Viral_PSSM.json", "w").write(canonical(block))
    print("wrote Togaviridae_Viral_PSSM.json")
    print("  %d features, %d rep contigs, %d profiles"
          % (len(feats), len(close),
             len(glob.glob(f"Alignments/{MOD}/*/pssms/*.pssm"))))
    for k in ORDER:
        f = feats[k]
        print("  %-8s %-4s bit %5d  len %5d-%-5d  ext %d/%d  %s"
              % (k, f["gene_symbol"], f["bit_cutoff"], f["min_len"], f["max_len"],
                 f["upstream_ext"], f["downstream_ext"], f["anno"]))


main()
