#!/usr/bin/env python3
"""Regenerate ARTIFACTS.md from reports/published.tsv.

The URLs were getting lost. They lived in a RESUME file, in prose, and in one
half-complete table, and three of the forty-five appeared nowhere at all. This
makes one index, generated rather than maintained by hand, so it cannot drift
from the thing it describes.

Two distinctions the hand-written version got wrong and this one enforces:

  * A page with a SOURCE FILE but no live URL was built and never published.
    That is not the same as a page that was never made, and collapsing them
    hides finished work sitting on disk.
  * When one title has been published more than once, the CURRENT one is the
    one with the latest date -- not the one that happened to come first in the
    listing. The listing is only roughly ordered, and taking its order made
    Rhabdoviridae's 3 September registry current over its 9 September one.

Source files are matched on each file's own <title>, never on its filename, so
renaming a file cannot silently unlink it.

    python3 reports/gen_artifacts_index.py
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

TAXA = ["Orthoflavivirus", "Hepaciviridae", "Pestiviridae", "Pegivirus", "Alphaflexiviridae", "Allexivirus",
        "Hepeviridae", "Tobamovirus", "Trivirinae", "Matonaviridae",
        "Togaviridae", "Rhabdoviridae"]
KINDS = [("Coverage Audit", "coverage audit"),
         ("PSSM Registry", "PSSM registry"),
         ("String Collapse", "string collapse"),
         ("Vocabulary Saturation", "vocabulary saturation")]
#  Pages whose title does not follow "<taxon> <kind>".
ALIAS = {("Matonaviridae", "Vocabulary Saturation"): "Rubella Vocabulary Saturation"}


def load():
    rows = []
    for line in open(os.path.join(HERE, "published.tsv")):
        if line.startswith("#") or not line.strip():
            continue
        p = line.rstrip("\n").split("\t")
        if len(p) == 3:
            rows.append((p[0].strip(), p[1].strip(), p[2].strip()))
    return rows


def sources():
    by = {}
    for f in sorted(os.listdir(HERE)):
        if not f.endswith(".html"):
            continue
        m = re.search(r"<title>([^<]*)</title>",
                      open(os.path.join(HERE, f), errors="replace").read())
        if m and m.group(1).strip():
            by.setdefault(m.group(1).strip(), f)
    return by


def main():
    rows, src = load(), sources()

    #  Latest date wins. Ties keep the first seen, which only happens when the
    #  same page was republished the same day and either URL is the same page.
    best = {}
    for t, u, d in rows:
        if t not in best or d > best[t][1]:
            best[t] = (u, d)
    superseded = [(t, u, d) for t, u, d in rows if best[t][0] != u]

    def title_for(tax, kind):
        return ALIAS.get((tax, kind), "%s %s" % (tax, kind))

    def row(t):
        u, d = best[t]
        s = "[source](reports/%s)" % src[t] if t in src else "—"
        return "| %s | [open](https://claude.ai/artifact/%s) | %s | %s |" % (t, u, s, d)

    o = ["# Published artifacts", "",
         "Every page this project has published, with its live URL and its source",
         "in this repo. **Artifacts live on claude.ai, not on GitHub** — a `.html`",
         "file here renders locally in a browser; the `open` link is the shared",
         "copy. Pages are private until shared from the page's own share menu, so",
         "a link will not open for someone who has not been given access.", "",
         "Generated by `reports/gen_artifacts_index.py` from",
         "`reports/published.tsv`. Do not edit this file — refresh the TSV from",
         "`Artifact list` in a Claude Code session and re-run the script.", "",
         "## Per taxon", ""]

    used = set()
    for tax in TAXA:
        live, built, never = [], [], []
        for kind, label in KINDS:
            t = title_for(tax, kind)
            used.add(t)
            if t in best:
                live.append(t)
            elif t in src:
                built.append((label, src[t]))
            else:
                never.append(label)
        if not (live or built):
            continue
        o += ["### %s" % tax, "", "| page | live | source | updated |", "|---|---|---|---|"]
        o += [row(t) for t in live]
        o.append("")
        if built:
            o.append("Built but never published, source is here: " +
                     ", ".join("[%s](reports/%s)" % (l, f) for l, f in built) + ".")
        if never:
            o.append("Not made: " + ", ".join(never) + ".")
        if built or never:
            o.append("")

    rest = sorted((t for t in best if t not in used), key=lambda t: best[t][1], reverse=True)
    o += ["## Not tied to one taxon", "", "| page | live | source | updated |",
          "|---|---|---|---|"] + [row(t) for t in rest] + [""]

    o += ["## Superseded", "",
          "The same title published more than once. The tables above carry the",
          "current URL; these earlier ones still resolve and should not be",
          "circulated.", "", "| page | live | updated |", "|---|---|---|"]
    o += ["| %s | [open](https://claude.ai/artifact/%s) | %s |" % (t, u, d)
          for t, u, d in sorted(superseded, key=lambda r: (r[0], r[2]))]
    o.append("")

    open(os.path.join(ROOT, "ARTIFACTS.md"), "w").write("\n".join(o) + "\n")
    print("ARTIFACTS.md: %d published, %d current, %d superseded"
          % (len(rows), len(best), len(superseded)))
    nosrc = sorted(t for t in best if t not in src)
    if nosrc:
        print("no source file in reports/ for %d:" % len(nosrc))
        for t in nosrc:
            print("   -", t)
    return 0


sys.exit(main())
